vars:
  - project:
      aws: cads-it
      directory: .
stages:
  get_training_dataset:
    cmd: python3 -m src.get_training_dataset --config=params.yaml
    deps:
      - src/get_training_dataset.py
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/input/player_attributes_salaries_dataset.csv
      - ./data/input/nba_games_training_dataset.csv