#TODO: Create a step to validate the dataframe using python pacakge
#TODO: All varaibles as params for DVC
# Feature Store
#TODO https://github.com/feast-dev/feast-gcp-driver-ranking-tutorial/blob/master/predict.py
vars:
  - project:
      aws: cads-it
      directory: .
stages:
  get_training_dataset:
    cmd: python3 -m src.get_training_dataset --config=params.yaml
    deps:
      - src/get_training_dataset.py
      - player_attributes_salaries_dataset.csv
      - nba_gamelog_schedule_dataset.csv
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/input/player_attributes_salaries_dataset.csv
      - ./data/input/nba_gamelog_schedule_dataset.csv
  pre_cleaning_dataset:
    cmd: python3 -m src.pre_cleaning_dataset --config=params.yaml
    deps:
      - src/pre_cleaning_dataset.py
      - ./data/input/nba_gamelog_schedule_dataset.csv
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/processed/nba_games_training_dataset_pre_cleaned.csv
  features_engineering_pipeline:
    cmd: python3 -m src.features_engineering --config=params.yaml
    deps:
      - src/features_engineering.py
      - ./data/processed/nba_games_training_dataset_pre_cleaned.csv
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/processed/nba_games_training_dataset_cleaned_w_features.csv
  get_y_variables:
    cmd: python3 -m src.get_y_variables --config=params.yaml
    deps:
      - src/get_y_variables.py
      - ./data/processed/nba_games_training_dataset_cleaned_w_features.csv
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/processed/nba_games_training_dataset_final.csv
  post_cleaning_dataset:
    cmd: python3 -m src.post_cleaning_dataset --config=params.yaml
    deps:
      - src/post_cleaning_dataset.py
      - ./data/processed/nba_games_training_dataset_final.csv
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/output/nba_games_training_dataset_final_post_cleaned.csv
  training_dataset_assessment:
    cmd: python3 -m src.training_dataset_assessment --config=params.yaml
    deps:
      - src/training_dataset_assessment.py
      - ./data/output/nba_games_training_dataset_final_post_cleaned.csv
    params:
      - base
      - get_training_dataset
  load_training_dataset_to_csv:
    cmd: python3 -m src.load_training_dataset_to_csv --config=params.yaml
    deps:
      - src/load_training_dataset_to_csv.py
      - ./data/output/nba_games_training_dataset_final_post_cleaned.csv
    params:
      - base
      - get_training_dataset

      




      