vars:
  - project:
      aws: cads-it
      directory: .
stages:
  get_training_dataset:
    cmd: python3 -m src.get_training_dataset --config=params.yaml
    deps:
      - src/get_training_dataset.py
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/input/player_attributes_salaries_dataset.csv
      - ./data/input/nba_games_training_dataset.csv
  pre_cleaning_dataset:
    cmd: python3 -m src.pre_cleaning_dataset --config=params.yaml
    deps:
      - src/pre_cleaning_dataset.py
      - ./data/input/nba_games_training_dataset.csv
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/processed/nba_games_training_dataset_pre_cleaned.csv
  features_engineering_pipeline:
    cmd: python3 -m src.features_engineering --config=params.yaml
    deps:
      - src/features_engineering.py
      - ./data/processed/nba_games_training_dataset_pre_cleaned.csv
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/processed/nba_games_training_dataset_cleaned_w_features.csv
  # previous_games_average_features:
  #   cmd: python3 -m src.previous_games_average_features --config=params.yaml
  #   deps:
  #     - src/previous_games_average_features.py
  #   params:
  #     - base
  #     - get_training_dataset
  #   outs:
  #     - ./data/processed/nba_games_training_dataset_previous_games_features.csv
  # elo_features:
  #   cmd: python3 -m src.elo_features --config=params.yaml
  #   deps:
  #     - src/elo_features.py
  #   params:
  #     - base
  #     - get_training_dataset
  #   outs:
  #     - ./data/processed/nba_games_training_dataset_elo_features.csv
  # previous_games_ratio_average_features:
  #   cmd: python3 -m src.previous_games_ratio_average_features --config=params.yaml
  #   deps:
  #     - src/previous_games_ratio_average_features.py
  #   params:
  #     - base
  #     - get_training_dataset
    # outs:
    #   - ./data/processed/nba_games_training_dataset_ratio_average_features.csv




      