vars:
  - project:
      aws: cads-it
      directory: .
stages:
  get_training_dataset:
    cmd: python3 -m src.get_training_dataset --config=params.yaml
    deps:
      - src/get_training_dataset.py
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/input/player_attributes_salaries_dataset.csv
      - ./data/input/nba_games_training_dataset.csv
  pre_cleaning_dataset:
    cmd: python3 -m src.pre_cleaning_dataset --config=params.yaml
    deps:
      - src/pre_cleaning_dataset.py
      - ./data/input/nba_games_training_dataset.csv
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/processed/nba_games_training_dataset_pre_cleaned.csv
  features_engineering_pipeline:
    cmd: python3 -m src.features_engineering --config=params.yaml
    deps:
      - src/features_engineering.py
      - ./data/processed/nba_games_training_dataset_pre_cleaned.csv
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/processed/nba_games_training_dataset_cleaned_w_features.csv
  get_y_variables:
    cmd: python3 -m src.get_y_variables --config=params.yaml
    deps:
      - src/get_y_variables.py
      - ./data/processed/nba_games_training_dataset_cleaned_w_features.csv
    params:
      - base
      - get_training_dataset
    outs:
      - ./data/processed/nba_games_training_dataset_final.csv
  load_training_dataset_to_db:
    cmd: python3 -m src.load_training_dataset_to_db --config=params.yaml
    deps:
      - src/load_training_dataset_to_db.py
      - ./data/processed/nba_games_training_dataset_cleaned_w_features.csv
    params:
      - base
      - get_training_dataset

      




      